version: '3.7'

services:
  opendeck-ui:
    container_name: opendeck-ui
    image: paradajz168/opendeck-ui
    volumes:
      - $PWD:/home/ubuntu/OpenDeckUI
    working_dir: /home/ubuntu/OpenDeckUI
    command: tail -f /dev/null