import { markRaw } from "vue";
import {
  Block,
  IBlockDefinition,
  ISectionDefinition,
  SectionType,
  FormInputComponent,
} from "../../interface";
import { deviceStore } from "../../../store";

import GlobalForm from "./GlobalForm.vue";
import GlobalFirmware from "./GlobalFirmware.vue";
import GlobalIcon from "./GlobalIcon.vue";

const makeOscDestinationSections = (
  destination: number,
  settingIndex: number,
): Dictionary<ISectionDefinition> => ({
  [`OscDest${destination}Ipv4Octet0`]: {
    block: Block.Global,
    key: `oscDest${destination}Ipv4Octet0`,
    type: SectionType.Setting,
    section: 3,
    settingIndex,
    min: 0,
    max: 255,
    component: FormInputComponent.Input,
    label: `Destination ${destination} IPv4 octet 1`,
    helpText: `First octet of OSC destination ${destination} IPv4 address.`,
  },
  [`OscDest${destination}Ipv4Octet1`]: {
    block: Block.Global,
    key: `oscDest${destination}Ipv4Octet1`,
    type: SectionType.Setting,
    section: 3,
    settingIndex: settingIndex + 1,
    min: 0,
    max: 255,
    component: FormInputComponent.Input,
    label: `Destination ${destination} IPv4 octet 2`,
    helpText: `Second octet of OSC destination ${destination} IPv4 address.`,
  },
  [`OscDest${destination}Ipv4Octet2`]: {
    block: Block.Global,
    key: `oscDest${destination}Ipv4Octet2`,
    type: SectionType.Setting,
    section: 3,
    settingIndex: settingIndex + 2,
    min: 0,
    max: 255,
    component: FormInputComponent.Input,
    label: `Destination ${destination} IPv4 octet 3`,
    helpText: `Third octet of OSC destination ${destination} IPv4 address.`,
  },
  [`OscDest${destination}Ipv4Octet3`]: {
    block: Block.Global,
    key: `oscDest${destination}Ipv4Octet3`,
    type: SectionType.Setting,
    section: 3,
    settingIndex: settingIndex + 3,
    min: 0,
    max: 255,
    component: FormInputComponent.Input,
    label: `Destination ${destination} IPv4 octet 4`,
    helpText: `Fourth octet of OSC destination ${destination} IPv4 address.`,
  },
  [`OscDest${destination}Port`]: {
    block: Block.Global,
    key: `oscDest${destination}Port`,
    type: SectionType.Setting,
    section: 3,
    settingIndex: settingIndex + 4,
    min: 1,
    max: 65535,
    component: FormInputComponent.Input,
    label: `Destination ${destination} port`,
    helpText: `UDP port on OSC destination ${destination}.`,
  },
});

const sections: Dictionary<ISectionDefinition> = {
  ...makeOscDestinationSections(1, 0),
  ...makeOscDestinationSections(2, 5),
  ...makeOscDestinationSections(3, 10),
  ...makeOscDestinationSections(4, 15),
  OscListenPort: {
    block: Block.Global,
    key: "oscListenPort",
    type: SectionType.Setting,
    section: 3,
    settingIndex: 20,
    min: 1,
    max: 65535,
    component: FormInputComponent.Input,
    label: "Listen port",
    helpText: `UDP port OpenDeck listens on for incoming OSC packets.`,
  },
  OscRestrictIncomingToDestIp: {
    block: Block.Global,
    key: "oscRestrictIncomingToDestIp",
    type: SectionType.Setting,
    section: 3,
    settingIndex: 21,
    component: FormInputComponent.Toggle,
    label: "Restrict incoming OSC",
    helpText: `Accept incoming OSC packets only from configured destination IPv4 addresses.`,
  },
  PreservePresetState: {
    block: Block.Global,
    key: "preservePresetState",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 1,
    component: FormInputComponent.Toggle,
    label: "Preserve preset setting",
    helpText: `When disabled, first preset will always be loaded on device power on.
      Otherwise, preset specified with "Active preset" option is remembered. This is not related to saving of configuration
      to specified preset - the configuration data is always retained even after power off.`,
  },
  DisableForcedValueRefreshAfterPresetChange: {
    block: Block.Global,
    key: "disableForcedValueRefreshAfterPresetChange",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 2,
    component: FormInputComponent.Toggle,
    label: "Disable forced value refresh after preset change",
    helpText: `If this option isn't enabled, all components will resend their current values once the preset changes.`,
  },
  EnablePresetChangeWithProgramChangeIn: {
    block: Block.Global,
    key: "enablePresetChangeWithProgramChangeIn",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 3,
    component: FormInputComponent.Toggle,
    label: "Enable preset change with MIDI Program Change In",
    helpText: `When enabled, upon receiving MIDI Program Change message (on any interface and any channel) the board will change the preset to cooresponding program change value.`,
  },
  ActivePreset: {
    block: Block.Global,
    key: "activePreset",
    type: SectionType.Setting,
    section: 2,
    settingIndex: 0,
    component: FormInputComponent.Select,
    // Note: Read supported preset count from state
    options: (): any => {
      const count = deviceStore.state.supportedPresetsCount || 1;
      const options = [];
      for (let value = 0; value < count; value++) {
        options.push({
          value,
          text: String(value + 1),
        });
      }
      return options;
    },
    // Note: update separate state property (different UI segment than the form) when loading value
    onLoad: (value: number): void => {
      deviceStore.state.activePreset = value;
    },
    label: "Active preset",
    helpText: `Selects which preset is currently active. Presets store preset-scoped configuration, while some global system settings are stored separately.`,
  },
  UseGlobalChannel: {
    block: Block.Global,
    key: "useGlobalChannel",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 13,
    component: FormInputComponent.Toggle,
    label: "Use global channel",
    helpText: `When enabled, specified global MIDI channel will be used for all components. Individual channels for components will be ignored.`,
  },
  GlobalChannel: {
    showIf: (formState: FormState): boolean => !!formState.useGlobalChannel,
    block: Block.Global,
    key: "globalChannel",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 14,
    min: 1,
    max: 17,
    component: FormInputComponent.Input,
    label: "Global channel",
    helpText: `Setting the channel to value 17 will cause sending of data on each MIDI channel, and incoming channel for outputs and other components will be ignored.`,
  },
  StandardNoteOff: {
    block: Block.Global,
    key: "standardNoteOff",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 0,
    component: FormInputComponent.Toggle,
    label: "Standard note off",
    helpText: `When disabled, Note On with velocity 0 will be sent as note off. If enabled, true Note Off event will be sent instead.`,
  },
  RunningStatus: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "runningStatus",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 1,
    component: FormInputComponent.Toggle,
    label: "Running status",
    helpText: `This setting applies only to DIN MIDI out. When enabled,
    MIDI output bandwidth increases due to lower amount of bytes being sent. This setting can cause issues on older MIDI gear so it's best to leave it disabled.`,
  },
  MIDIClock: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "midiClock",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 15,
    component: FormInputComponent.Toggle,
    label: "Send MIDI clock on DIN",
    helpText: `This setting applies only to DIN MIDI out.
    When enabled, MIDI clock will be sent out at default BPM of 120. The tempo can be changed with switches or encoders.`,
  },
  DinMidiState: {
    block: Block.Global,
    key: "dinMidiState",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 3,
    component: FormInputComponent.Toggle,
    label: "DIN MIDI",
    helpText: `Enable or disable DIN MIDI switch and output.`,
  },
  BleMidiState: {
    block: Block.Global,
    key: "bleMidiState",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 9,
    component: FormInputComponent.Toggle,
    label: "BLE MIDI",
    helpText: `Enable or disable BLE (Bluetooth Low Energy) MIDI switch and output.`,
  },
  UsbToDinThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "usbToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 4,
    component: FormInputComponent.Toggle,
    label: "USB to DIN Thru",
    helpText: `When enabled, all data received via USB will be forwarded to DIN out.`,
  },
  UsbToUsbThru: {
    block: Block.Global,
    key: "usbToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 5,
    component: FormInputComponent.Toggle,
    label: "USB to USB Thru",
    helpText: `When enabled, all data received via USB will be forwarded to USB out.`,
  },
  UsbToBleThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "usbToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 6,
    component: FormInputComponent.Toggle,
    label: "USB to BLE Thru",
    helpText: `When enabled, all data received via USB will be forwarded to BLE out.`,
  },
  DinToDinThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "dinToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 7,
    component: FormInputComponent.Toggle,
    label: "DIN to DIN Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to DIN out.`,
  },
  DinToUsbThru: {
    showIf: (formState: FormState): boolean => !!formState.dinMidiState,
    block: Block.Global,
    key: "dinToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 2,
    component: FormInputComponent.Toggle,
    label: "DIN to USB Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to USB out.`,
  },
  DinToBleThru: {
    showIf: (formState: FormState): boolean =>
      !!formState.dinMidiState && !!formState.bleMidiState,
    block: Block.Global,
    key: "dinToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 8,
    component: FormInputComponent.Toggle,
    label: "DIN to BLE Thru",
    helpText: `When enabled, all data received via DIN will be forwarded to BLE out.`,
  },
  BleToDinThru: {
    showIf: (formState: FormState): boolean =>
      !!formState.dinMidiState && !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToDinThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 10,
    component: FormInputComponent.Toggle,
    label: "BLE to DIN Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to DIN out.`,
  },
  BleToUsbThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToUsbThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 11,
    component: FormInputComponent.Toggle,
    label: "BLE to USB Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to USB out.`,
  },
  BleToBleThru: {
    showIf: (formState: FormState): boolean => !!formState.bleMidiState,
    block: Block.Global,
    key: "bleToBleThru",
    type: SectionType.Setting,
    section: 0,
    settingIndex: 12,
    component: FormInputComponent.Toggle,
    label: "BLE to BLE Thru",
    helpText: `When enabled, all data received via BLE will be forwarded to BLE out.`,
  },
};

export const GlobalBlock: IBlockDefinition = {
  block: Block.Global,
  title: "Global",
  routeName: "device-global",
  iconComponent: markRaw(GlobalIcon),
  sections,
  routes: [
    {
      path: "",
      name: "device-global",
      component: GlobalForm,
    },
    {
      path: "firmware-update",
      name: "device-firmware-update",
      component: GlobalFirmware,
    },
  ],
};
