import { IBlockDefinition, FormInputComponent, DefinitionType } from ".";

export const defaultEncoderData: Dictionary<number> = {
  enabled: (null as unknown) as number,
  invertDirection: (null as unknown) as number,
  encodingMode: (null as unknown) as number,
  midiIdLSB: (null as unknown) as number,
  midiChannel: (null as unknown) as number,
  pulsesPerStep: (null as unknown) as number,
  acceleration: (null as unknown) as number,
  midiIdMSB: (null as unknown) as number,
  remoteSync: (null as unknown) as number,
};

export const EncoderSectionDefinitions: Dictionary<IBlockDefinition> = {
  Enabled: {
    key: "enabled",
    type: DefinitionType.ComponentValue,
    section: 0,
    component: FormInputComponent.Toggle,
    label: "Enabled",
    helpText: `Enables or disables encoder. All encoders are disabled by default.`,
  },
  InvertDirection: {
    key: "invertDirection",
    type: DefinitionType.ComponentValue,
    section: 1,
    component: FormInputComponent.Toggle,
    label: "Invert direction",
    helpText: `When enabled, encoder will send inverted MIDI CC messages in different directions. Default option is disabled for all encoders.`,
  },
  EncodingMode: {
    key: "encodingMode",
    type: DefinitionType.ComponentValue,
    section: 2,
    component: FormInputComponent.Select,
    options: [
      { value: 0, text: "Control change - 7Fh01h" },
      { value: 1, text: "Control change - 3Fh41h" },
      { value: 2, text: "Program change" },
      { value: 3, text: "Control change -Continuous 7-bit" },
      { value: 8, text: "Control change - Continuous 14-bit" },
      { value: 4, text: "Change preset" },
      { value: 5, text: "Pitch bend" },
      { value: 6, text: "NRPN/7-bit" },
      { value: 7, text: "NRPN/14-bit" },
    ],
    label: "Invert direction",
    helpText: `Denotes encoder encoding mode. Default option is 7Fh01h for all encoders.`,
  },
  MidiIdLSB: {
    key: "midiIdLSB",
    type: DefinitionType.ComponentValue,
    section: 3,
    component: FormInputComponent.Input,
    min: 0,
    max: 127,
    label: "MIDI ID LSB",
    helpText: "MIDI LSB channel for current component",
  },
  MidiChannel: {
    key: "midiChannel",
    type: DefinitionType.ComponentValue,
    section: 4,
    component: FormInputComponent.Input,
    min: 0,
    max: 10,
    label: "MIDI channel",
    helpText: "Denotes the MIDI CC number for each encoder.",
  },
  PulsesPerStep: {
    key: "pulsesPerStep",
    type: DefinitionType.ComponentValue,
    section: 5,
    component: FormInputComponent.Select,
    options: [
      { value: 2, text: "2" },
      { value: 3, text: "3" },
      { value: 4, text: "4" },
    ],
    label: "Pulses per step",
    helpText: `Amount of pulses encoder generates for single step.`,
  },
  Acceleration: {
    key: "acceleration",
    type: DefinitionType.ComponentValue,
    section: 6,
    component: FormInputComponent.Select,
    options: [
      { value: 0, text: "Disabled" },
      { value: 1, text: "Slow" },
      { value: 2, text: "Medium" },
      { value: 3, text: "Fast" },
    ],
    label: "Acceleration",
    helpText: `-`,
  },
  MidiIdMSB: {
    key: "midiIdMSB",
    type: DefinitionType.ComponentValue,
    section: 7,
    component: FormInputComponent.Input,
    min: 0,
    max: 127,
    label: "MIDI ID MSB",
    helpText: "MIDI MSB channel for current component",
  },
  RemoteSync: {
    key: "remoteSync",
    type: DefinitionType.ComponentValue,
    section: 8,
    component: FormInputComponent.Toggle,
    label: "Remote sync",
    helpText: "-",
  },
};
